apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-07-12T04:31:30Z"
  labels:
    version: v1
    zone: prod
  name: nginx1
  namespace: default
  resourceVersion: "24955"
  uid: c8be6960-f6d9-48a6-82c1-90be6beb71f1
spec:
  containers:
  - image: edison954/nginx:v1
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hnqzs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-hnqzs
    secret:
      defaultMode: 420
      secretName: default-token-hnqzs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-12T04:31:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-07-12T04:31:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-07-12T04:31:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-07-12T04:31:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://6195c7a9a4fa11eb2792a7cfca63e7d072973ec0efd83a1db350b380e1db3410
    image: docker.io/edison954/nginx:v1
    imageID: docker.io/edison954/nginx@sha256:4b90277a57a4f416d52aeacc7d42773a297751d5c81d93a66cbbe1c17f13e975
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-12T04:31:47Z"
  hostIP: 192.168.64.2
  phase: Running
  podIP: 10.244.0.4
  podIPs:
  - ip: 10.244.0.4
  qosClass: BestEffort
  startTime: "2021-07-12T04:31:30Z"
